<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit32be9bbdf13b11a3b60df7308fdb042c
{
    public static $firstCharsPsr4 = array (
        't' => true,
        'a' => true,
    );

    public static $prefixDirsPsr4 = array (
        'think\\composer\\' => 
        array (
            0 => __DIR__ . '/..' . '/topthink/think-installer/src',
        ),
        'app\\' => 
        array (
            0 => __DIR__ . '/../..' . '/application',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->firstCharsPsr4 = ComposerStaticInit32be9bbdf13b11a3b60df7308fdb042c::$firstCharsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit32be9bbdf13b11a3b60df7308fdb042c::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
